<a href="https://colab.research.google.com/github/zannoa/hidroponik/blob/master/Data_Zanno(A11_2018_11074).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [4]:
dataset = pd.read_csv('Data.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [5]:
print(x)

[['Semarang' 1.0 72.0]
 ['Pekalongan' nan 43.0]
 ['Batang' 4.0 24.0]
 ['Ungaran' 3.0 88.0]
 ['Pekalongan' 3.0 nan]
 ['Semarang' 2.0 15.0]
 ['Ungaran' 5.0 63.0]
 ['Kendal' 3.0 7.0]
 ['Batang' 5.0 8.0]
 ['Demak' 5.0 60.0]]


In [7]:
print(y)

['Tidak' 'Ya' 'Ya' 'Ya' 'Tidak' 'Tidak' 'Ya' 'Tidak' 'Tidak' 'Ya']


In [9]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder = 'passthrough')
x = np.array(ct.fit_transform(x))

In [10]:
print(x)

[[0.0 0.0 0.0 0.0 1.0 0.0 1.0 72.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 nan 43.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 4.0 24.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 3.0 88.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 3.0 nan]
 [0.0 0.0 0.0 0.0 1.0 0.0 2.0 15.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 5.0 63.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 3.0 7.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 5.0 8.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 5.0 60.0]]


In [11]:
print(y)

['Tidak' 'Ya' 'Ya' 'Ya' 'Tidak' 'Tidak' 'Ya' 'Tidak' 'Tidak' 'Ya']


In [12]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)


In [13]:
print(y)

[0 1 1 1 0 0 1 0 0 1]


In [14]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

In [15]:
print(x_train)

[[0.0 0.0 0.0 0.0 0.0 1.0 5.0 63.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 3.0 nan]
 [0.0 0.0 0.0 0.0 1.0 0.0 1.0 72.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 3.0 88.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 nan 43.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 3.0 7.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 5.0 8.0]
 [0.0 0.0 0.0 0.0 1.0 0.0 2.0 15.0]]


In [16]:
print(x_test)

[[1.0 0.0 0.0 0.0 0.0 0.0 4.0 24.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 5.0 60.0]]


In [17]:
print(y_train)

[1 0 0 1 1 0 0 0]


In [18]:
print(y_test)

[1 1]


In [20]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [21]:
print(x_train)

[[0.0 0.0 0.0 -0.5773502691896258 -0.5773502691896258 1.7320508075688774
  1.3703203194062978 0.6762718391685768]
 [0.0 0.0 0.0 1.7320508075688774 -0.5773502691896258 -0.5773502691896258
  -0.10540925533894598 nan]
 [0.0 0.0 0.0 -0.5773502691896258 1.7320508075688774 -0.5773502691896258
  -1.5811388300841898 0.9701002934280274]
 [0.0 0.0 0.0 -0.5773502691896258 -0.5773502691896258 1.7320508075688774
  -0.10540925533894598 1.4924619898892728]
 [0.0 0.0 0.0 1.7320508075688774 -0.5773502691896258 -0.5773502691896258
  nan 0.02331971859201989]
 [0.0 0.0 1.0 -0.5773502691896258 -0.5773502691896258 -0.5773502691896258
  -0.10540925533894598 -1.1519940984457826]
 [1.0 0.0 0.0 -0.5773502691896258 -0.5773502691896258 -0.5773502691896258
  1.3703203194062978 -1.1193464924169547]
 [0.0 0.0 0.0 -0.5773502691896258 1.7320508075688774 -0.5773502691896258
  -0.8432740427115678 -0.8908132502151597]]


In [22]:
print(x_test)

[[1.0 0.0 0.0 -0.5773502691896258 -0.5773502691896258 -0.5773502691896258
  0.632455532033676 -0.5969847959557092]
 [0.0 1.0 0.0 -0.5773502691896258 -0.5773502691896258 -0.5773502691896258
  1.3703203194062978 0.5783290210820933]]
